[package]
name = "yote_recordstore_rust"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["lib"]
[dependencies]
named-lock = "0.4.1"
serde_bytes = "0.11"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tempfile = "3"
byteorder = "1"
thiserror = "1.0"