[package]
name = "recordstore_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bincode = "1.3"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "2.0", features = ["derive", "parsing" ] }
